# Generated by Django 5.0.2 on 2024-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODS_Flux_total_dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.CharField(max_length=250)),
                ('libelle_region', models.CharField(max_length=250)),
                ('code_departement', models.CharField(max_length=250)),
                ('libelle_departement', models.CharField(max_length=250)),
                ('date_fin_semaine', models.CharField(max_length=250)),
                ('type_de_vaccin', models.CharField(max_length=250)),
                ('nucd', models.CharField(max_length=250)),
                ('nb_dose', models.CharField(max_length=250)),
            ],
        ),
    ]
