# Generated by Django 5.0.2 on 2024-02-25 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_dates',
            fields=[
                ('pk_date', models.DateField(default='1900-01-01', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_type_vaccin',
            fields=[
                ('pk_type_vaccin', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('pk_departement', models.CharField(default=None, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('code_departement', models.CharField(blank=True, default=None, max_length=250)),
                ('code_region', models.CharField(default=None, max_length=250)),
                ('libelle_region', models.CharField(blank=True, default=None, max_length=250)),
                ('libelle_departement', models.CharField(blank=True, default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ODS_Flux_total_dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.CharField(max_length=250)),
                ('code_departement', models.CharField(max_length=250)),
                ('libelle_region', models.CharField(max_length=250)),
                ('libelle_departement', models.CharField(max_length=250)),
                ('date_fin_semaine', models.CharField(max_length=250)),
                ('type_de_vaccin', models.CharField(max_length=250)),
                ('nb_ucd', models.CharField(max_length=250)),
                ('nb_doses', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='F_doses',
            fields=[
                ('pk_F_doses', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nb_ucd', models.IntegerField(blank=True, default=None, null=True)),
                ('nb_doses', models.IntegerField(blank=True, default=None, null=True)),
                ('code_departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vaccins.departement')),
                ('pk_date', models.ForeignKey(default='1900-01-01', on_delete=django.db.models.deletion.CASCADE, to='app_vaccins.d_dates')),
                ('pk_type_vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vaccins.d_type_vaccin')),
            ],
            options={
                'ordering': ['code_departement', 'pk_date'],
            },
        ),
    ]
