# Generated by Django 5.0.2 on 2024-02-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaccins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ods_flux_total_dep',
            old_name='nucd',
            new_name='nb_ucd',
        ),
    ]
